# Generated by Django 5.2.12 on 2026-03-07 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
    ]
